// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: strings.proto

package grpc.examples.strings;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.Empty)
    com.google.protobuf.MessageOrBuilder {
}
