// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: strings.proto

package grpc.examples.strings;

public interface LengthResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.LengthResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
