// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: strings.proto

package grpc.examples.strings;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.strings.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.strings.Message.Enum detail = 1;</code>
   */
  grpc.examples.strings.Message.Enum getDetail();
}
