// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: strings.proto

package grpc.examples.strings;

public interface MultiMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.MultiMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .strings.StringRequest multirequest = 1;</code>
   */
  java.util.List<grpc.examples.strings.StringRequest> 
      getMultirequestList();
  /**
   * <code>repeated .strings.StringRequest multirequest = 1;</code>
   */
  grpc.examples.strings.StringRequest getMultirequest(int index);
  /**
   * <code>repeated .strings.StringRequest multirequest = 1;</code>
   */
  int getMultirequestCount();
  /**
   * <code>repeated .strings.StringRequest multirequest = 1;</code>
   */
  java.util.List<? extends grpc.examples.strings.StringRequestOrBuilder> 
      getMultirequestOrBuilderList();
  /**
   * <code>repeated .strings.StringRequest multirequest = 1;</code>
   */
  grpc.examples.strings.StringRequestOrBuilder getMultirequestOrBuilder(
      int index);
}
